#!/bin/bash
#PBS -q normal
#PBS -l select=1:ncpus=24:mem=1G
#PBS -l walltime=10:00:00
#PBS -P 14001280

## Run FastQC on all fastq files ##
source ~/miniconda3/etc/profile.d/conda.sh
conda activate base

WKDIR=/home/projects/14001280/PROJECTS/blood_microbiome

for j in `seq 5`
do 
	in=${WKDIR}/data/temp_files/0${j}_fastq
	out=${WKDIR}/results/qc/fastqc_reports/0${j}_fastq
#	echo $out

	for i in ${in}/*
	do
		echo $i		
		fastqc \
			-t 24 \
			${i} \
			-o ${out}

	done
done

